export interface Product {
    id: number;
    title: string;
    price: number;
    description: string;
    qty: number;
    image: string;
  }
export const products = [
    {
        "id": 1,
        "title": "Day Old Chicks",
        "description": "Qualiry Layers Chick ",
        "price": 350,
        "category": "Chick",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540167/Day-Old-1_qtr7ci.png",
        "location": "Eleyele, Ibadan",
    },
    {
        "id": 2,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 3,
        "title": "Old Layer",
        "description": "Quality Old Layers for Meat",
        "price": 3000,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540246/Chicken_bvp5we.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 4,
        "title": "Crates of Free Eggs",
        "description": "Eggs",
        "price": "950",
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540189/aliment-background-healthy-eggshell-brown_a5gwub.jpg",
        "location": "Ijebu-Ode, Ogun",
    }
    , {
        "id": 2,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 5,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 6,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 7,
        "title": "GSD Pup",
        "description": "Pedigree German Shepherd pup",
        "price": 130000.00,
        "category": "Dogs",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674543327/GJ36SVHwT4yI1Zf0tsc3_lefcoy.png",
        "location": "Maryland, Lagos",
    },
    {
        "id": 8,
        "title": "Feeder",
        "description": "Quality Layers Chick ",
        "price": 10500,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674542536/6lbfeeder_425x577_woupuu.png",
        "location": "Oshodi, Lagos",
    },
    {
        "id": 9,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price":1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    }, {
        "id": 10,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    }, 
    {
        "id": 11,
        "title": "Crates of Free Eggs",
        "description": "Eggs",
        "price": 850,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540189/aliment-background-healthy-eggshell-brown_a5gwub.jpg",
        "location": "Surulere, Lagos",
    }, 
    {
        "id": 12,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    }, 
    {
        "id": 12,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": "1200",
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    }, 
    {
        "id": 13,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 14,
        "title": "Day Old Chicks",
        "description": "Qualiry Layers Chick ",
        "price": 390,
        "category": "Chick",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540167/Day-Old-1_qtr7ci.png",
        "location": "Agodi, Ibadan",
    },
    {
        "id": 15,
        "title": "GSD Pup",
        "description": "Pedigree German Shepherd pup",
        "price": 170000.00,
        "category": "Dogs",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674542949/young-dog_ynixyq.jpg",
        "location": "Maryland, Lagos",
    },
    {
        "id": 16,
        "title": "Point of Lay",
        "description": "Qualiry Layers Chick ",
        "price": 1200,
        "category": "Chicken",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540194/old_skvqky.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 17,
        "title": "Bully Max",
        "description": "Builds long-lasting Muscle 100% Safe: no side effects, no mood changesNo exercise is required For all breeds age 7 weeks and older.Safe for pregnant & nursing dogs.",
        "price": 12500,
        "category": "Pet Supplies",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540789/bullymax_imjtn2.jpg",
        "location": "Ijebu-Ode, Ogun",
    },
    {
        "id": 18,
        "title": "Day Old Chicks",
        "description": "Qualiry Layers Chick ",
        "price": 450,
        "category": "Chick",
        "image": "https://res.cloudinary.com/netpoc-inc/image/upload/v1674540167/Day-Old-1_qtr7ci.png",
        "location": "Akure, Ondo State",
    },
]